title: Electron
email: atom@github.com
description: 'Build cross platform desktop apps with web technologies'
baseurl: 'http://electron.atom.io'
twitter_username: ElectronJS
github_username: atom
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
gems:
    - jekyll-redirect-from
latest_version: v0.36.0
current_node: 4.1.1
current_chrome: 45.0.2454.85
current_v8: 4.5.103.29
available_versions:
    - v0.24.0
    - v0.25.0
    - v0.26.0
    - v0.27.0
    - v0.28.0
    - v0.29.0
    - v0.30.0
    - v0.31.0
    - v0.32.0
    - v0.33.0
    - v0.34.0
    - v0.35.0
    - v0.36.0
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Grunfile.js
    - package.json
    - script
    - spec
