on:
  push:
    branches:
      - master

name: Update source data

jobs:
  updateElectronDataPackages:
    name: Auto-update Electron data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Switch to update branch
        run: |
          if git branch --remotes | grep -q origin/update-data; then
            git checkout update-data
          else
            git checkout -b update-data
          fi
      - run: npm run update-data
      - name: Commit package update changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "machine github.com login $GITHUB_ACTOR password $GITHUB_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
          git add package.json package-lock.json
          if test -n "$( git status -s)"; then
            git config user.name "$GITHUB_ACTOR"
            git config user-email "electron-bot@users.noreply.github.com"
            git diff
            git commit -m "build(deps): update electron data packages"
            git push origin
            node --unhandled-rejections=strict .github/actions/create-pr.js
          else
            echo No update needed
          fi
